### ISSUE TITLE
Large caches left in image

### ISSUE THREAD

**Issue by kouril** [REMnux/docker#42]
The Docker image contains two large(r) cache directories:

699M	/var/cache/salt
274M	/root/.cache

these look like some installation artifacts, could they be removed from the image?

**Comment by lennyzeltser** [comment]
Thanks for noticing! In a VM, I prefer to keep /var/cache/salt untouched, because I think it aids with faster upgrades. However, I think people will be less likely to update the distro inside the container and will instead periodically refresh the container image from Docker Hub. I'll take a closer look at removing contents of both cache directories from the Docker image, as saving a GB of disk space sounds very nice.

**Comment by lennyzeltser** [comment]
Done. The updated REMnux image file is 1 GB less than before. Thanks, @kouril!
